### ISSUE TITLE
When Drag & Drop more gems than 1 on tool, entire stack is removed instead of one piece from stack

### ISSUE THREAD

**Issue by DexterSK** [FN-FAL113/FN-FAL-s-Amplifications#110]
**Describe the bug**
When Drag & Drop more gems than 1 on tool, entire stack is removed instead of one piece from stack.
Didn't looked at the code but this probably can be easily fixed with something like this
```java
if( item.getAmount() > 1 )
    item.setAmount( item.getAmount() - 1 );
else
    player.getInventory().removeItem( item );
``` 

**To Reproduce (Important)**
1. Give eg. 64x Telepathy Gem
2. Put stack of gems to tool
3. All 64 pieces will be removed instead of one piece from stack

**Expected behavior**
Remove only one item from itemstack

**Screenshots**

**Server Log**
doesn't matter

**Environment (REQUIRED)**
 - Server Software and Version (Spigot/Paper): Paper
 - Minecraft version: git-Purpur-2083 (MC: 1.20.2)*
 - Slimefun version: DEV - 1104 (git c977454e)
 - FNAmplification version: DEV - 93 (git 7bc01100)

**Comment by FN-FAL113** [comment]
Will be fixed on next update

**Comment by FN-FAL113** [comment]
Fixed on build 95, please download latest build from https://blob.builds which has the new auto updater

**Comment by DexterSK** [comment]
> Fixed on build 95, please download latest build from https://blob.build which has the new auto updater

Please fix tier 2 etc too, seems like you have fixed only tier 1 gems. thanks

**Comment by FN-FAL113** [comment]
> > Fixed on build 95, please download latest build from https://blob.build which has the new auto updater
> 
> Please fix tier 2 etc too, seems like you have fixed only tier 1 gems. thanks

Next update, forgot they are different implementation.
