### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by DexterSK** [FN-FAL113/FN-FAL-s-Amplifications#114]
**Describe the bug**

**To Reproduce (Important)**
1. Right click with Mysterious Stick on:
2.   - Any log / Any weathered/waxed copper that you can clean with axe
4. Break it
5. It will drop another Mysterious Stick

**Expected behavior**
Drop original item instead of Mysterios Stick

**Screenshots**
doesn't matter

**Server Log**
doesn't matter

**Environment (REQUIRED)**
doesn't matter

 - Server Software and Version (Spigot/Paper): doesn't matter
 - Minecraft version: doesn't matter
 - Slimefun version: doesn't matter
 - FNAmplification version: doesn't matter

**Comment by DexterSK** [comment]
> Thank you for making an issue report, I will check it out.

also should work with shovels & grass block, idk if you fixed it too

**Comment by FN-FAL113** [comment]
> > Thank you for making an issue report, I will check it out.
> 
> also should work with shovels & grass block, idk if you fixed it too

what server version?

**Comment by FN-FAL113** [comment]
I need such details as this bug does not work on newer mc server versions

**Comment by FN-FAL113** [comment]
also which shovels are u referring to,  please state specific item from the addon.

**Comment by FN-FAL113** [comment]
Can't unfortunately fix such stuff without needed details. Please create a new issue report with proper reproduction of any bugs. Thank you. This particular issue is now fixed.
