### ISSUE TITLE
Newer Music Disks Break Jukebox

### ISSUE THREAD

**Issue by lati00lati** [FN-FAL113/FN-FAL-s-Amplifications#118]
**Describe the bug**
Playing "5" or "Relic" music disks from the Jukebox cause the Jukebox to disappear. I've only confirmed this for Jukebox III but I assume it's the same for I and II.

**To Reproduce (Important)**
1. Place a Jukebox III
2. Hook it up to Power
3. Start playing "5" or "Relic" disks
4. Watch as the block disappears. This may cause other blocks to disappear as well.

**Expected behavior**
It should start playing the "5" or "Relic" disk instead of breaking.

**Screenshots**
Kind of hard to get a screenshot, it just disappears though.

**Server Log**

https://pastebin.com/wvaknREn

**Environment (REQUIRED)**

 - Server Software and Version (Spigot/Paper): Paper
 - Minecraft version: 1.20.4
 - Slimefun version:  Slimefun Dev - 1133
 - FNAmplification version: FNAmplifications Dev - 101

**Comment by FN-FAL113** [comment]
Thank you for reporting, I check it out.
