### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sky-3311** [FN-FAL113/FN-FAL-s-Amplifications#125]
**Describe the bug**

**To Reproduce (Important)**
1.download it
2.restart server
3.see error
**Expected behavior**

**Screenshots**

**Server Log**

https://mclo.gs/DHX1bUw
**Environment (REQUIRED)**

![image](https://github.com/user-attachments/assets/4abea3cb-5081-4680-a168-040ca7a2fe67)
![image](https://github.com/user-attachments/assets/de4da4a6-7596-46ea-bf14-88b2264b49cb)

![image](https://github.com/user-attachments/assets/30b7ff31-6329-47c5-87e0-82488a024e71)
Slimefun-dev-build 1156
 - FNAmplification version:[Build 106](https://blob.build/dl/FNAmplifications/Dev/106)
[58f92c96](https://github.com/FN-FAL113/FN-FAL-s-Amplifications/commit/58f92c96d7c12121576be4a21aa816773f01b268)

**Comment by FN-FAL113** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce (Important)** Steps to reproduce the behavior: 1.download it 2.restart server 3.see error **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Server Log**
> 
> https://mclo.gs/DHX1bUw **Environment (REQUIRED)**
> 
> ![image](https://private-user-images.githubusercontent.com/175519518/373846291-4abea3cb-5081-4680-a168-040ca7a2fe67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MjkxLTRhYmVhM2NiLTUwODEtNDY4MC1hMTY4LTA0MGNhN2EyZmU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWY0OGFiODI2ZWU4NWMzNzZhZTg5YmYzMmFlZWYwYTFlZGFjZWVkYzNiY2RjNDZhZWJjM2M5OTNmODE5YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4jRmuobNuCp5adgKNtHGx5IE5-Db_6A1GAcLtrx83b4) ![image](https://private-user-images.githubusercontent.com/175519518/373846310-de4da4a6-7596-46ea-bf14-88b2264b49cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MzEwLWRlNGRhNGE2LTc1OTYtNDZlYS1iZjE0LTg4YjIyNjRiNDljYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGY3MWM4MTJmNmRmOGIxZTg5MDVmMGQxMzlkMDNlZDE1YThiN2FmZTMzNTQxYjI5MjYyOGZiZjk1YjRkOWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tMkyXSpgIMBd7H4-wpQsSQSSOORJE3jyLxVCkQnaZkI)
> 
> ![image](https://private-user-images.githubusercontent.com/175519518/373846335-30b7ff31-6329-47c5-87e0-82488a024e71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MzM1LTMwYjdmZjMxLTYzMjktNDdjNS04N2UwLTgyNDg4YTAyNGU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjZhOTc1YzE2OWM2OTYwNjNmN2U3ODE4Zjc1ZTVlZmQ4ZmY5OThhY2YwYzY3Mzc2YmRjMWEwNjM1ZjcwYTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b0CKrLisJ3Rg9PPdqECFrqRgBegOyBNBe6xBzp0ubzI) Slimefun-dev-build 1156
> 
> * FNAmplification version:[Build 106](https://blob.build/dl/FNAmplifications/Dev/106)
>   [58f92c96](https://github.com/FN-FAL113/FN-FAL-s-Amplifications/commit/58f92c96d7c12121576be4a21aa816773f01b268)

Please use updated paper

**Comment by sky-3311** [comment]
[i update the paper 
This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
but it still do not work
https://mclo.gs/GhU6pdq
](https://mclo.gs/GhU6pdq)


> > **描述 bug**对 bug 是什么的清晰简洁的描述。
> > **重现 （重要）**重现行为的步骤： 1.下载它 2.重新启动服务器 3.查看错误 **预期行为** 清晰简洁地描述您预期会发生的情况。
> > **屏幕截图**如果适用，请添加屏幕截图以帮助解释您的问题。
> > **服务器日志**
> > https://mclo.gs/DHX1bUw **环境 （必需）**
> > ![图像](https://private-user-images.githubusercontent.com/175519518/373846291-4abea3cb-5081-4680-a168-040ca7a2fe67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MjkxLTRhYmVhM2NiLTUwODEtNDY4MC1hMTY4LTA0MGNhN2EyZmU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWY0OGFiODI2ZWU4NWMzNzZhZTg5YmYzMmFlZWYwYTFlZGFjZWVkYzNiY2RjNDZhZWJjM2M5OTNmODE5YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4jRmuobNuCp5adgKNtHGx5IE5-Db_6A1GAcLtrx83b4) ![图像](https://private-user-images.githubusercontent.com/175519518/373846310-de4da4a6-7596-46ea-bf14-88b2264b49cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MzEwLWRlNGRhNGE2LTc1OTYtNDZlYS1iZjE0LTg4YjIyNjRiNDljYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGY3MWM4MTJmNmRmOGIxZTg5MDVmMGQxMzlkMDNlZDE1YThiN2FmZTMzNTQxYjI5MjYyOGZiZjk1YjRkOWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tMkyXSpgIMBd7H4-wpQsSQSSOORJE3jyLxVCkQnaZkI)
> > ![图像](https://private-user-images.githubusercontent.com/175519518/373846335-30b7ff31-6329-47c5-87e0-82488a024e71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjQ1MTIsIm5iZiI6MTcyODEyNDIxMiwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODQ2MzM1LTMwYjdmZjMxLTYzMjktNDdjNS04N2UwLTgyNDg4YTAyNGU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjZhOTc1YzE2OWM2OTYwNjNmN2U3ODE4Zjc1ZTVlZmQ4ZmY5OThhY2YwYzY3Mzc2YmRjMWEwNjM1ZjcwYTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b0CKrLisJ3Rg9PPdqECFrqRgBegOyBNBe6xBzp0ubzI)Slimefun-dev-build 1156
> > 
> > * FNAmplification 版本：[Build 106](https://blob.build/dl/FNAmplifications/Dev/106) [58f92c96](https://github.com/FN-FAL113/FN-FAL-s-Amplifications/commit/58f92c96d7c12121576be4a21aa816773f01b268)
> 
> 请使用更新的纸张

[i update the paper 
This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
but it still do not work
https://mclo.gs/GhU6pdq

**Comment by FN-FAL113** [comment]
> i update the paper This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) but it still do not work https://mclo.gs/GhU6pdq

what slimefun fork are you using

**Comment by sky-3311** [comment]
> > i update the paper This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) but it still do not work https://mclo.gs/GhU6pdq
> 
> what slimefun fork are you using? can I get a link to download the jar. Thanks

https://blob.build/dl/Slimefun4/Dev/1156

**Comment by FN-FAL113** [comment]
> > > i update the paper This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) but it still do not work https://mclo.gs/GhU6pdq
> > 
> > 
> > what slimefun fork are you using? can I get a link to download the jar. Thanks
> 
> https://blob.build/dl/Slimefun4/Dev/1156

Thats official slimefun and it doesn't support 1.21 yet, your screenshot is unofficial slimefun.

**Comment by sky-3311** [comment]
Slimefun-538e41a-Beta.jar,I'm sure I'm using the official one

**Comment by FN-FAL113** [comment]
> Slimefun-538e41a-Beta.jar,I'm sure I'm using the official one The plugin didn't work after one of my reboots, he can work before i restart my server

You are using a chinese fork of slimefun, that is not official. If you can link me to that chinese fork I can maybe try it out. The output for /sf versions for official slimefun should look like this and looking at your console logs slimefun is in chinese language.

![image](https://github.com/user-attachments/assets/1728590b-2490-471f-8f43-cefb1e914746)

**Comment by sky-3311** [comment]
I used this version before I used the official version
https://builds.guizhanss.com/r2/SlimefunGuguProject/Slimefun4/master/Slimefun-0021742-Beta.jar
I didn't delete the config file but used the official jar

**Comment by FN-FAL113** [comment]
Pushed a fixed. Please test it again using latest build (107). Thanks

**Comment by xiaofengv233** [comment]
> I used this version before I used the official version https://builds.guizhanss.com/r2/SlimefunGuguProject/Slimefun4/master/Slimefun-0021742-Beta.jar I didn't delete the config file but used the official jar ![image](https://private-user-images.githubusercontent.com/175519518/373867127-60bb9326-bc33-4950-9054-959c29badb84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTMwMDgsIm5iZiI6MTcyODI5MjcwOCwicGF0aCI6Ii8xNzU1MTk1MTgvMzczODY3MTI3LTYwYmI5MzI2LWJjMzMtNDk1MC05MDU0LTk1OWMyOWJhZGI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwOTE4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTZlNTI5NWNjOThmMzczYWZlN2JjODM3NzE2MGNiNjU4ZjkzZTEyZDc0ZTkyYjM4NGVlNDg5MTAzM2EyMTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0AJG8M3bNX14UxhcK7rj6q96PNyPas2yk39Wm-oHynI)

哥们 你解决了吗?我的也突然变红了,一样是 1.21.1,插件都是最新版

**Comment by sky-3311** [comment]
![image](https://github.com/user-attachments/assets/120a6fae-a53c-4aea-8671-d9283856c70b)
解决了

**Comment by xiaofengv233** [comment]
> ![image](https://private-user-images.githubusercontent.com/175519518/374116414-120a6fae-a53c-4aea-8671-d9283856c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ0NTAsIm5iZiI6MTcyODI5NDE1MCwicGF0aCI6Ii8xNzU1MTk1MTgvMzc0MTE2NDE0LTEyMGE2ZmFlLWE1M2MtNGFlYS04NjcxLWQ5MjgzODU2YzcwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwOTQyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjAwYjUwNWY4NzEzMWIxNjk2NjVhMzc1YzgxNjk0NmE5MThhYTlhMGM3NWQ0M2ExZDBmYzFmMmViZmYxY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NuWA00ymxYoU2bhypreq_ZVJ6IWbOmLd8ylY0upgyrI) 解决了

怎么解决的?是鬼斩的那个吗

**Comment by FN-FAL113** [comment]
> > ![image](https://private-user-images.githubusercontent.com/175519518/374116414-120a6fae-a53c-4aea-8671-d9283856c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ0NTAsIm5iZiI6MTcyODI5NDE1MCwicGF0aCI6Ii8xNzU1MTk1MTgvMzc0MTE2NDE0LTEyMGE2ZmFlLWE1M2MtNGFlYS04NjcxLWQ5MjgzODU2YzcwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwOTQyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjAwYjUwNWY4NzEzMWIxNjk2NjVhMzc1YzgxNjk0NmE5MThhYTlhMGM3NWQ0M2ExZDBmYzFmMmViZmYxY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NuWA00ymxYoU2bhypreq_ZVJ6IWbOmLd8ylY0upgyrI)Solved
> 
> How did you solve it? Is it the one from Ghost Slash?

download latest here
https://blob.build/project/FNAmplifications

**Comment by xiaofengv233** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/175519518/374116414-120a6fae-a53c-4aea-8671-d9283856c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTQ0NTAsIm5iZiI6MTcyODI5NDE1MCwicGF0aCI6Ii8xNzU1MTk1MTgvMzc0MTE2NDE0LTEyMGE2ZmFlLWE1M2MtNGFlYS04NjcxLWQ5MjgzODU2YzcwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwOTQyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjAwYjUwNWY4NzEzMWIxNjk2NjVhMzc1YzgxNjk0NmE5MThhYTlhMGM3NWQ0M2ExZDBmYzFmMmViZmYxY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NuWA00ymxYoU2bhypreq_ZVJ6IWbOmLd8ylY0upgyrI)Solved
> > 
> > 
> > How did you solve it? Is it the one from Ghost Slash?
> 
> download latest here https://blob.build/project/FNAmplifications

Thanks
