### ISSUE TITLE
half recipe :(

### ISSUE THREAD

**Issue by RIPISDRAD** [FN-FAL113/FN-FAL-s-Amplifications#2]
hey there 
![2021-11-02_20 19 19](https://user-images.githubusercontent.com/76468672/139909641-7cd0f5b5-ffb9-4fc1-961a-433c6d492d75.png)
as u can see page 3 half recipe is here and the rest is next page better be together

**Comment by RIPISDRAD** [comment]
ok it can be see in almost every machine
and not just 1 page

**Comment by FN-FAL113** [comment]
> hey there ![2021-11-02_20 19 19](https://user-images.githubusercontent.com/76468672/139909641-7cd0f5b5-ffb9-4fc1-961a-433c6d492d75.png) as u can see page 3 half recipe is here and the rest is next page better be together

Thank you for the report, due to the limitations in displaying the recipes as seen in your picture, it cannot be displayed uniformedly but I'll try my best in the next updates to improve them

**Comment by FN-FAL113** [comment]
> ok it can be see in almost every machine and not just 1 page

Check out the latest update made some changes on that :)
