### ISSUE TITLE
Staff of Cobweb replaces the blocks, items or anything where it spawns the cobwebs.

### ISSUE THREAD

**Issue by Boomer-1** [FN-FAL113/FN-FAL-s-Amplifications#43]
Fal, watch the video I've linked

https://youtu.be/LmWICkbYkGc

when i right clicked the cobweb staff, it replaced my IE storage units, my network storage units, but apparantly also left block data behind as you'll see the signs stay and actually update

**Comment by FN-FAL113** [comment]
appreciate the report will get fixed in the next build
