### ISSUE TITLE
holograms remain when breaking the power generators

### ISSUE THREAD

**Issue by Boomer-1** [FN-FAL113/FN-FAL-s-Amplifications#56]
After placing all 12 power generators and letting the buffers fill up, i broke all 12 generators, 4 holograms remained, and 2 had to be replaced and broken twice to remove them.

**Comment by FN-FAL113** [comment]
This is a common issue with holograms just like in core slimefun. I can't seem to reproduce it,  did happen once before build 52 but the solution is the same which is placing the block again and breaking it.

**Comment by FN-FAL113** [comment]
https://user-images.githubusercontent.com/88238718/158041628-e12a2baa-92d9-4a53-aad8-2842b4ff991e.mp4

**Comment by FN-FAL113** [comment]
https://user-images.githubusercontent.com/88238718/158041641-98c92e88-88ff-437a-a6a4-8079d987f029.mp4

The messages in the chat are debug messages, they do show correctly to determine if the hologram is removed but sometimes it won't work due to how holograms work in slimefun

**Comment by Boomer-1** [comment]
yeah figured it was that. just wanted you to be aware.

**Comment by FN-FAL113** [comment]
Appreciate your time with this. Seems others are having issue based on the slimefun discord recently on 1.18 above
