### ISSUE TITLE
console gem bug

### ISSUE THREAD

**Issue by zwrumpy** [FN-FAL113/FN-FAL-s-Amplifications#67]
versions:
- airplane paper 1.17.1
- slimefun rc 30
- fn ampli 62

server log
https://pastebin.com/RRKxnEUa

**Comment by FN-FAL113** [comment]
Can't seem to reproduce this on airplaine 1.17.1 or even paper 1.17.1

**Comment by FN-FAL113** [comment]
Itemstacks with broken nbt tags affects this probably
