### ISSUE TITLE
Tri-sword does player damage in none PVP worldguard regions and Factions Safe Zones

### ISSUE THREAD

**Issue by cybermancerr** [FN-FAL113/FN-FAL-s-Amplifications#74]
Players are able to do damage to eachother with the Tri-sword in NONE PVP worldguard regions and SafeZones with FactionsUUID.  Tri-sword does not respect PVP region flags.

**Comment by FN-FAL113** [comment]
provide addon versions, etc

**Comment by FN-FAL113** [comment]
only works on tri sword? or other throwables are fine like damnation or axe throwie?

**Comment by cybermancerr** [comment]
/sf versions ouput:
SensibleToolbox vDEV - 46 (git 904daaed)
SfChunkInfo vDEV - 4 (git 1859e1a8)
FNAmplifications vDEV - 64 (git a701f9d8)
SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
DynaTech vDEV - 160 (git e1075a1c)
ExtraGear vDEV - 13 (git c62047e2)
SFAdvancements vDEV - 14 (git 682f7776)
CMILib v1.1.2.4
InfinityExpansion vDEV - 137 (git 4b326e08)
SFCalc vDEV - 37 (git dfc0fc41)
ElectricSpawners vDEV - 23 (git 6ec96773)
EMC2 vDEV - 11 (git 89b4400a)
ExtraHeads vDEV - 23 (git 0b59a770)
VillagerUtil vDEV - 1 (git 0a949b19)
MobCapturer vDEV - 17 (git c21b00a5)
SlimyTreeTaps vDEV - 20 (git 963f0383)
FlowerPower vDEV - 13 (git 06ad45dc)
SlimeTinker vDEV - 72 (git bb2ef153)
TranscEndence vDEV - 41 (git 98d7d47e)
Galactifun vDEV - 59 (git 871aec03)
FluffyMachines vDEV - 111 (git 51416696)
DyedBackpacks vDEV - 17 (git 8b329e96)
SoundMuffler vDEV - 23 (git 2030f464)
AlchimiaVitae vDEV - 19 (git 24ffb2a5)
HardcoreSlimefun v1.0
SlimefunWarfare vDEV - 79 (git 11f4e7e9)
EcoPower vDEV - 5 (git 5c1ecd68)
ExoticGarden vDEV - 78 (git 7f9a5f63)
HeadLimiter vDEV - 13 (git 8c976b11)
DankTech2 vDEV - 4 (git 803760fb)
Liquid vDEV - 14 (git 0f5346bf)
LiteXpansion vDEV - 174 (git e36d509d)
SFMobDrops vDEV - 6 (git d36aba47)
SimpleUtils vDEV - 15 (git 4250fd5e)
ElementManipulation vDEV - 18 (git ce2c6165)
SoulJars vDEV - 23 (git b8358a1f)
EquivalencyTech v${project.version}
SimpleStorage vDEV - 10 (git ea5e5637)
PotionExpansion vDEV - 5 (git e2cfcd8a)
SlimyRepair vDEV - 4 (git 790c41cb)

its on the bloodheroes server.  We can test for you the throw stuff but I think just the PVP worldguard flags are being ignored in general.

**Comment by FN-FAL113** [comment]
I seem to have found the culprit, make sure your region is protected vertically 
https://youtu.be/pYAk38Hekqg?t=238
redefine the world guard regions you have, and use "//expand vert" command just like as what the guy did in the video above

**Comment by cybermancerr** [comment]
We are aware of that and the world guard flag for that is “invincibility”, which works in admin regions like spawn and safe zones, but for PVE only world setting “invincibility” flag set on the __global__ region that selects the entire world including vert would break survival game play.  Currently the entire world has PVP DENY flag for the __global__ region effectively disabling PVP.  Players using tri-sword or any throw weapons from FN add on are effectively bypassing PVP restrictions in that world.  We need a way to disable FN weapons from doing damage to players only.  Does not have to be world guard.  I’m open to any suggestions.
