### ISSUE TITLE
Server Log Error

### ISSUE THREAD

**Issue by zwrumpy** [FN-FAL113/FN-FAL-s-Amplifications#85]
**Describe the bug**
Server Log Error

**To Reproduce (Important)**
None

**Server Log**
https://gist.github.com/zwrumpy/9c5ec8d981d30dccc640136b20b04f22

**Environment (REQUIRED)**
- Airplane paper 1.17

 - Server Software and Version (Spigot/Paper):
 - Minecraft version: 1.17
 - Slimefun version: #1014
 - FNAmplification version: #72

**Comment by FN-FAL113** [comment]
Please provide reproduction steps
