### ISSUE TITLE
Feature Request:  changelog option

### ISSUE THREAD

**Issue by mrcoffee1026** [FN-FAL113/FN-FAL-s-Amplifications#89]
Could you please add an OPTION to display or not the changelog you ammend to the MOTD upon connect.  While this is informative, it does is not information that matters to every player since not all players get into Slimefun or haven't yet... even fewer will have advanced into the FN-FAL-s-Amplifications addon, and most of the material discussed here can be overwhelming and possibly cause a person to not even want to begin.  Thank you so much!  Super Addon!

**Comment by FN-FAL113** [comment]
> Could you please add an OPTION to display or not the changelog you ammend to the MOTD upon connect. While this is informative, it does is not information that matters to every player since not all players get into Slimefun or haven't yet... even fewer will have advanced into the FN-FAL-s-Amplifications addon, and most of the material discussed here can be overwhelming and possibly cause a person to not even want to begin. Thank you so much! Super Addon!

one does exist already in the config.yml, you can disable changelog chat notif there
