### ISSUE TITLE
FN Assembler Station Exception on Empty Multiblock Craft

### ISSUE THREAD

**Issue by N1kyZ** [FN-FAL113/FN-FAL-s-Amplifications#99]
When players try to make the FN Assembler Station, and when clicking on the fence, it gives an error in the console
https://pastebin.com/Gfwhzab2

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

Purpur git-Purpur-1428 (MC: 1.17.1)
Slimefun DEV - 1043 (git 4bfc4f06)
Metrics-Module #28
Java 17

Installed Addons: (2)
  FNAmplifications vDEV - 84 (git dbbefc59)
  SFAdvancements vDEV - 23 (git 854eed14)
 
 EDIT: This only happens if there's nothing in it.

**Comment by FN-FAL113** [comment]
Thank you for reporting, have you tried running the server on paper or spigot if the issue still persist?

**Comment by N1kyZ** [comment]
I just tested it, same error
https://pastebin.com/q5PQkHpD

Paper git-Paper-411 (MC: 1.17.1)
Slimefun DEV - 1043 (git 4bfc4f06)
Metrics-Module #28
Java 17

Installed Addons: (2)
  FNAmplifications vDEV - 84 (git dbbefc59)
  SFAdvancements vDEV - 23 (git 854eed14)

**Comment by FN-FAL113** [comment]
Aight will take a look at it when I got the time, appreciate it

**Comment by FN-FAL113** [comment]
![image](https://user-images.githubusercontent.com/88238718/219697410-2787b278-7132-4042-a9ea-0c3d9ac6b9d7.png)
![image](https://user-images.githubusercontent.com/88238718/219697452-73a475cf-6eef-42f0-83f0-16380badf44c.png)
also working fine on 1.17.1
please provide accurate reproduction step or a video on this

**Comment by FN-FAL113** [comment]
tested on git-paper-399

**Comment by FN-FAL113** [comment]
PS: I managed to reproduce it after crafting many items concurrently and emptying the multiblock
